name: CI/CD for Blood Donation App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify installation

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Build Docker images
    - name: Build Docker images
      run: |
        docker build -t user-service ./user-service
        docker build -t donor-service ./donor-service
        docker build -t mysql-db ./database

    # Run containers with Docker Compose
    - name: Run containers with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d --build

    # Wait for MySQL and Services to be Ready
    - name: Wait for user-service to be ready
      run: |
        retries=30
        until curl --silent --fail http://user-service:4001/test-endpoint || [ $retries -eq 0 ]; do
          echo "Waiting for user-service to be ready..."
          sleep 5
          retries=$((retries-1))
        done
        if [ $retries -eq 0 ]; then
          echo "user-service is not ready after 30 attempts, failing..."
          docker-compose logs user-service
          exit 1
        fi

    - name: Wait for donor-service to be ready
      run: |
        retries=30
        until curl --silent --fail http://donor-service:5001/test-endpoint || [ $retries -eq 0 ]; do
          echo "Waiting for donor-service to be ready..."
          sleep 5
          retries=$((retries-1))
        done
        if [ $retries -eq 0 ]; then
          echo "donor-service is not ready after 30 attempts, failing..."
          docker-compose logs donor-service
          exit 1
        fi

    # Debug logs if services fail
    - name: Check logs of user-service
      if: failure()
      run: docker-compose logs user-service

    - name: Check logs of donor-service
      if: failure()
      run: docker-compose logs donor-service

    # Run tests
    - name: Run tests
      run: |
        curl http://user-service:4001/test-endpoint # Test user-service
        curl http://donor-service:5001/test-endpoint # Test donor-service

    # Shut down containers
    - name: Shut down containers
      run: docker-compose down

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Tag and Push Docker images to Docker Hub
    - name: Push Docker images to Docker Hub
      run: |
        docker tag user-service ${{ secrets.DOCKER_USERNAME }}/user-service:latest
        docker tag donor-service ${{ secrets.DOCKER_USERNAME }}/donor-service:latest
        docker tag mysql-db ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest

        docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/donor-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/mysql-db:latest

env:
  DB_HOST: mysql
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PORT: 3306
