name: CI/CD for Blood Donation App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build user-service Docker image
      run: |
        docker-compose up --build -d user-service ./user-service

    - name: Build donor-service Docker image
      run: |
        docker build -t donor-service ./donor-service

    - name: Build MySQL Docker image
      run: |
        docker build -t mysql-db ./database

    - name: Set up Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Run containers with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for MySQL, user-service, and donor-service to be ready
      run: |
        # Wait for MySQL container to be ready
        until docker-compose run mysql mysqladmin --user=root --password=root --host=mysql --port=3306 ping --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
        # Wait for user-service to be ready
        retries=30
        until curl --silent --fail http://localhost:4000/test-endpoint || [ $retries -eq 0 ]; do
          echo "Waiting for user-service to be ready..."
          sleep 5
          retries=$((retries-1))
        done
        if [ $retries -eq 0 ]; then
          echo "user-service is not ready after 30 attempts, failing..."
          exit 1
        fi
        # Wait for donor-service to be ready
        until curl --silent --fail http://localhost:5001/test-endpoint; do
          echo "Waiting for donor-service to be ready..."
          sleep 5
        done

    - name: Run tests
      run: |
        # Running the actual tests after services are confirmed to be up
        curl http://localhost:4000/test-endpoint # Example test for user-service
        curl http://localhost:5001/test-endpoint # Example test for donor-service

    - name: Shut down containers
      run: |
        docker-compose down

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push user-service
        docker push donor-service
        docker push mysql-db
