name: CI/CD for Blood Donation App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build user-service Docker image
      run: |
        docker build -t user-service ./user-service

    - name: Build donor-service Docker image
      run: |
        docker build -t donor-service ./donor-service

    - name: Build MySQL Docker image
      run: |
        docker build -t mysql-db ./database

    - name: Run containers with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Run tests
      run: |
        # Assuming you have test scripts set up
        curl http://localhost:4000/test-endpoint # Example test for user-service
        curl http://localhost:5000/test-endpoint # Example test for donor-service

    - name: Shut down containers
      run: |
        docker-compose down

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push user-service
        docker push donor-service
        docker push mysql-db